image:
  - Visual Studio 2017
  - Ubuntu

stack: jdk 8
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  nodejs_version: "8"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

test_script:
  - sh: ./gradlew clean test
  - cmd: gradlew.bat clean test

# Don't actually build.
build: off